# Generated by Django 2.2.24 on 2021-12-12 09:35

from django.db import migrations, models
from datetime import datetime

def date_to_datetime(apps, schema_editor):
    event_model = apps.get_model('events', 'event')
    for event in event_model.objects.all():
        just_date = event.date_from
        if just_date:
            date_with_time = datetime(just_date.year, just_date.month, just_date.day, 10, 1, 1, 1)

            event.date_time_from = date_with_time
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20211212_1029'),
    ]

    operations = [
        # Copy date from "date_from" to "date_time_from" and add time
        migrations.RunPython(date_to_datetime),

        # Delete column "date_from"
        migrations.RemoveField(
            model_name='event',
            name='date_from',
        ),

        # Create "date_from" from "date_time_from"
        migrations.RenameField(
            model_name='event',
            old_name='date_time_from',
            new_name='date_from',
        ),
    ]
